import mysql.connector as msqlcon
mycon = msqlcon.connect(host = "localhost", user = "root", passwd = "040803", database = "db")
crsr = mycon.cursor()
sql1 = "Insert into student (Rollno, Name, Marks) values({}, '{}', {})".format(100,'Ram',78)
sql2 = "Insert into student (Rollno, Name, Marks) values({}, '{}', {})".format(101,'Shyam',74)
sql3 = "Insert into student (Rollno, Name, Marks) values({}, '{}', {})".format(103,'Mohan',76)
sql4 = "Insert into student (Rollno, Name, Marks) values({}, '{}', {})".format(104,'Krishna',75)
crsr.execute(sql1)
crsr.execute(sql2)
crsr.execute(sql3)
crsr.execute(sql4)
print("Record inserted succssefully!!")
mycon.commit()
mycon.close()
